### ISSUE TITLE
Main page shows "Apache Airflow&#174;" instead of "Apache Airflow®"

### ISSUE THREAD

**Issue by noamraph** [apache/airflow-site#1074]
See those sections:
![image](https://github.com/user-attachments/assets/af795597-5e13-4a45-a323-7fb76d35933b)
It shows  `Apache Airflow&#174;` instead of `Apache Airflow®`

**Comment by pierrejeambrun** [comment]
@noamraph Thanks for reporting that, it would be great if you could open a PR to fix that, it would really help :)
