### ISSUE TITLE
Ordering the contribution page correctly

### ISSUE THREAD

**Issue by Vain21s** [apache/airflow-site#1094]
### The order of the "Want to Contribute?" an "Are u a user can be placed one after the other" and the subpoints are not linearly matching it can be changed with "Are u a User?" being the first point instead of displaying both parallely

![Screenshot 2024-11-29 112744](https://github.com/user-attachments/assets/3bc5bfe7-79af-4d02-b0b2-0b7857d020e2)

**Comment by potiuk** [comment]
Why?

**Comment by potiuk** [comment]
Can you propose a PR with fix and how it will look like - on both mobila and wide screen ?

**Comment by Vain21s** [comment]
Yes , ofcourse I gonna work on it and put a pull request
