### ISSUE TITLE
Dag run twice in airflow

### ISSUE THREAD

**Issue by Annie0131** [apache/airflow-site#217]
![Screenshot from 2019-12-09 23-11-49](https://user-images.githubusercontent.com/26398961/70459068-67356780-1ad9-11ea-86a8-44d1bbfb574d.png)
As you can see the dag xyz_dag run twice a day and XYZ dag is the scheduled dag, not manual trigger for the first run it runs at 5:10:16 and the second run it ran at 5:10:58 similarly this behavior has been observed for my all 400 dags. I don't know why this behavior has occurred and I don't know how this can be solved any help will be appreciated. below I have shared xyx_dag.py file.

![image](https://user-images.githubusercontent.com/26398961/70460387-30ad1c00-1adc-11ea-8241-ce3dd6d7556c.png)

**Comment by mik-laj** [comment]
Unfortunately, this is a repository that contains the source code of the Airflow website.  You should create a ticket in the JIRA:
https://issues.apache.org/jira/projects/AIRFLOW/

**Comment by Annie0131** [comment]
Please check the below ticket.

https://issues.apache.org/jira/browse/AIRFLOW-6207
