### ISSUE TITLE
Fix link on Blog to GitHub, captioned "Suggest a change on this page"

### ISSUE THREAD

**Issue by impredicative** [apache/airflow-site#224]
On each blog page is a popup with a GitHub link captioned "Suggest a change on this page". This link on each page is currently broken. For example, the home page of the blog has a link to https://github.com/apache/airflow-site/edit/aip-11/landing-pages/site/content/en/blog/_index.md . This link should instead probably be https://github.com/apache/airflow-site/edit/master/landing-pages/site/content/en/blog/_index.md . Essentially, replacing `aip-11` with `master` could fix it.

**Comment by mik-laj** [comment]
I started working on it.

**Comment by mik-laj** [comment]
Fixed: https://github.com/apache/airflow-site/pull/227
