### ISSUE TITLE
Search on docs partly broken

### ISSUE THREAD

**Issue by ashb** [apache/airflow-site#232]
There are two search boxes in the docs - the one in the left hand nav works fine, but the search box in the results page doesn't.

`  <script type="text/javascript">$('#fallback').hide();</script>` in search.html complains that `$ is undefined`

**Comment by ryw** [comment]
Confirming https://airflow.apache.org/docs/stable/search.html search box is broken

**Comment by mik-laj** [comment]
@ryw  @ashb Can you check if this problem persists?

**Comment by ashb** [comment]
Fixed!
