### ISSUE TITLE
Update Links for Social Media Buttons

### ISSUE THREAD

**Issue by kaxil** [apache/airflow-site#236]
![image](https://user-images.githubusercontent.com/8811558/72750525-1f7b2300-3be3-11ea-8c2e-8dc35663d72b.png)

The links to the above button need to be updated, currently, they are set to the original website link github.com, slack.com etc

**Comment by louisguitton** [comment]
I think this has been fixed https://github.com/apache/airflow-site/blob/master/landing-pages/site/config.toml#L114-L137

**Comment by zhongjiajie** [comment]
Close this, but we should remove JIRA after we migrate all ticket to issue?

**Comment by zhongjiajie** [comment]
Thanks @louisguitton for the clarification
