### ISSUE TITLE
Typo in community page

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow-site#238]
Typo in page https://airflow.apache.org/community/

<img width="1126" alt="Community___Apache_Airflow" src="https://user-images.githubusercontent.com/11539188/73594121-6fbf8280-450b-11ea-8243-9bc11c0fa7ac.png">

**Comment by louisguitton** [comment]
I've opened a PR to fix the typo you pointed out, but actually the typo "commiter" instead of "committer" is everywhere around the codebase (even in CSS etc ...) but I didn't include that change in the PR.

**Comment by mik-laj** [comment]
@louisguitton Can you do separate PR to fix other typos?

**Comment by XD-DENG** [comment]
Thanks @louisguitton
