### ISSUE TITLE
./site.sh preview-landing-pages silently fails because of missing dependency

### ISSUE THREAD

**Issue by louisguitton** [apache/airflow-site#244]
Currently, if you run `./site.sh preview-landing-pages` the website doesn't start.
The script stops at the following line with no output
```
+ docker exec --tty --interactive --workdir /opt/site/docs-archive/ airflow-site-c ./show_docs_index_json.sh
```
Running that command outside the script shows:
```sh
$ ./show_docs_index_json.sh: line 25: jq: command not found
./show_docs_index_json.sh: line 25: jq: command not found
```

The workaround I found to still be able to preview the website when I make a change is to run 
```sh 
docker exec --tty --interactive --workdir /opt/site/landing-pages/ airflow-site-c npm run preview
```

**Comment by louisguitton** [comment]
Nevermind, I had an old docker image, and since this line doesn't force the rebuild, it was failing
https://github.com/apache/airflow-site/blob/18b03b8227c7b84ade3c007f9f7d25d66e4ec214/site.sh#L66

Running 
```sh 
docker build -t airflow-site .
```
fixed it

**Comment by mik-laj** [comment]
There is also a ready command to build a new image -  `bash site.sh build-image`,  but I prefer to use `bash site.sh cleanup`. This forces you to build a new image when you start a new container.
