### ISSUE TITLE
Version dropdown doesn't work on Module pages

### ISSUE THREAD

**Issue by kaxil** [apache/airflow-site#254]
It works on the mail page:
https://airflow.apache.org/docs/stable/

it doesn't work on internal pages:
https://airflow.apache.org/docs/stable/_modules/airflow/hooks/http_hook.html

![image](https://user-images.githubusercontent.com/8811558/75150225-d7788000-56fb-11ea-950f-946d434545ed.png)

**Comment by divyaguduru** [comment]
unable to reproduce this issue in UI .. looks like it's already addressed @kaxil @mik-laj

**Comment by kaxil** [comment]
Thanks @divyaguduru
