### ISSUE TITLE
Version dropdown does not include master

### ISSUE THREAD

**Issue by ad-m** [apache/airflow-site#270]
Hello,

I suggest add to dropdown of version link to master version ( https://airflow.readthedocs.io/en/latest/ ) of documentation:

![image](https://user-images.githubusercontent.com/3618479/86709881-acdbf380-c01a-11ea-935c-b7f040106a9a.png)

I agree that the default version should be stable. However, an additional link to go to the upcoming version can make find out documentation easier.

Kind regards

**Comment by mik-laj** [comment]
Unfortunately we cannot do this as it is against Apache release policy. The latest documentation can be found at: s.apache.org/airflow-docs

> Do not include any links on the project website that might encourage non-developers to download and use nightly builds, snapshots, release candidates, or any other similar package.

http://www.apache.org/legal/release-policy.html
