### ISSUE TITLE
Search page is not working correctly

### ISSUE THREAD

**Issue by XD-DENG** [apache/airflow-site#303]
The Search page is not working correctly (on my machine with Chrome, Safari, and Firefox).

For example, let's go to https://airflow.apache.org/docs/stable/search.html

Then if I click on whichever area indicated in the screenshot below, the page reloads immediately, including the input (when I click on the Input before I try to type anything, the page already starts to reload. So that user can not really enter anything).

<img width="1137" alt="Search_—_Airflow_Documentation" src="https://user-images.githubusercontent.com/11539188/98160091-fd3a6380-1edd-11eb-8f59-0d2a63b68851.png">

**Comment by XD-DENG** [comment]
CC @kaxil @mik-laj . May you please help confirm if you can reproduce this issue? Cheers

**Comment by mik-laj** [comment]
@XD-DENG I confirm. This search input is not working, but the search input in the side menu does work.
![Uploading Screenshot 2020-11-04 at 20.47.18.png…]()

**Comment by XD-DENG** [comment]
Thanks @mik-laj . Yep, the Search feature in the side menu is working fine.

**Comment by xiasiliang-hit** [comment]
it does work in two input search box
