### ISSUE TITLE
Fix partial of hidden text on the side-bar which located in REST API Reference

### ISSUE THREAD

**Issue by roharon** [apache/airflow-site#306]
Not shown partial of text(Endpoint path)  located in the right side-bar which located in [REST API Reference](https://airflow.apache.org/docs/stable/rest-api-ref.html)

*Dose not changed to the next line*

```html
<a class="reference internal" href="#post--api-experimental-dags--DAG_ID--dag_runs">POST /api/experimental/dags/&lt;DAG_ID&gt;/dag_runs</a>
```

<img src="https://user-images.githubusercontent.com/4939738/98500046-b1493f00-228e-11eb-9628-fc3f5ad91b09.png" alt="image" style="zoom:20%;" />
<br/>

**It seems to be problem caused by endpoint path that long.**
Also, hidden text amount is different each browser's zoom size

I think it must be shown like this image (that I modifed)
<img src="https://user-images.githubusercontent.com/4939738/98500530-0c2f6600-2290-11eb-91cb-c0069946dd4d.png" alt="image" style="zoom:25%;" />

**Comment by eladkal** [comment]
Fixed with the new API page
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html
