### ISSUE TITLE
The "Ecosystem" and "announcements" links are missing in documentation

### ISSUE THREAD

**Issue by potiuk** [apache/airflow-site#336]
The 2 links are missing in the documentation:

Compare this:

![Screenshot from 2020-12-09 09-49-32](https://user-images.githubusercontent.com/595491/101606658-e5d22700-3a03-11eb-8c3d-2b693b74d05b.png)

With this:

![Screenshot from 2020-12-09 09-49-05](https://user-images.githubusercontent.com/595491/101606718-f97d8d80-3a03-11eb-8bbf-cbcf5f87c4de.png)

**Comment by potiuk** [comment]
cc: @mik-laj -> could not find the place to fix it I think it's ok to just fix it for the upcoming 2.0 doc if fixing for 1.10.* will take time.

**Comment by mik-laj** [comment]
@potiuk https://github.com/apache/airflow/pull/12953 here is PR
Changing the archival documentation requires editing the HTML files, so I'll take a little more time.

**Comment by potiuk** [comment]
We can do it later :)
