### ISSUE TITLE
Add button / pointer / banner for Airflow Summit

### ISSUE THREAD

**Issue by kaxil** [apache/airflow-site#394]
We should add a button or pointer to promote Airflow Summit (https://airflowsummit.org/) on https://airflow.apache.org/

**Comment by kaxil** [comment]
cc @mik-laj @ryanahamilton @rbowen Can I get help from someone for this one

**Comment by kaxil** [comment]
cc @kgabryje  @mik-laj  Can I get help from someone for this one

**Comment by mik-laj** [comment]
@kaxil I am afraid that I will not have the capacity to deal with this anytime soon.

**Comment by turbaszek** [comment]
@kaxil how about simply adding a blogpost with short info about the Summit? We can add links and some important dates. WDYT?

**Comment by turbaszek** [comment]
https://github.com/apache/airflow-site/pull/396

**Comment by kaxil** [comment]
Thank You @turbaszek and @mik-laj
