### ISSUE TITLE
Transparency/better description of airflow on the website.

### ISSUE THREAD

**Issue by isConic** [apache/airflow-site#414]
I have no idea what airflow does or what a workflow is. I pieced this together from independent medium articles.

**Comment by potiuk** [comment]
Since you.already figured it out, maybe you could make a PR to make it clearer? This is a community manged project and if you as a newcomer could contribute to the docs to make it better and easier to understand, that would be fantastic.

Looking forward to your contributions !

**Comment by isConic** [comment]
I guess I can do that
Currently I am hesitant of mis-representing it. As Im stil not sure what airflow is. How would you describe airflow? What are some of the things/worflows that airflow has helped you with?  What IS a workflow? Why was this made? Any examples indicating what it's replacing?

**Comment by potiuk** [comment]
I personally have nothing more to add than this https://airflow.apache.org/docs/apache-airflow/stable/index.html -> for me it is self-explanatory. Not sure what else should be added.

**Comment by potiuk** [comment]
I think this page answers every single of your question in fact (including what it's replacing.... 

BTW. This is the page when you click on "Documentation" link in Airflow website.

**Comment by isConic** [comment]
Oh wow. Yes. This is everything I needed.   
Thanks

**Comment by potiuk** [comment]
Closing !
