### ISSUE TITLE
Links not updated on page footer

### ISSUE THREAD

**Issue by scouvreur** [apache/airflow-site#415]
There seems to be an issue in this page's footer - https://airflow.apache.org/docs/apache-airflow/stable/index.html

![Screenshot 2021-04-29 at 15 09 13](https://user-images.githubusercontent.com/34174735/116565114-76e76300-a8fd-11eb-9405-0eec10f2cff7.png)

Where the social media links do not point to specific Airflow accounts, but just to the generic sites eg. `https://www.youtube.com` instead of `https://www.youtube.com/channel/UCSXwxpWZQ7XZ1WL3wqevChA`. Also, the site points to the year being 2019, rather than 2021.

This seems to be fine in the landing page however - https://airflow.apache.org/

![Screenshot 2021-04-29 at 15 14 06](https://user-images.githubusercontent.com/34174735/116565232-94b4c800-a8fd-11eb-8454-7369dd94abbf.png)

Checking in the the code, this line though seems to point correctly to the footer urls:
https://github.com/apache/airflow-site/blob/d2a357fc7ea25338d13d193ab61a9202adbf95d9/sphinx_airflow_theme/sphinx_airflow_theme/footer.html#L76-L78

And this line seems to parse the date to get the current year:
https://github.com/apache/airflow-site/blob/d2a357fc7ea25338d13d193ab61a9202adbf95d9/sphinx_airflow_theme/sphinx_airflow_theme/footer.html#L107-L109

If there's anything I can do to help - let me know where to change this and I would be happy to open a PR !

**Comment by oreopot** [comment]
I can work on this and submit a PR.

**Comment by potiuk** [comment]
Feel free :)

**Comment by potiuk** [comment]
Hey @oreopot ? How is it going :)?

**Comment by oreopot** [comment]
Actually on the page the links are displayed correctly. Hence, I think this issue should be closed.
