### ISSUE TITLE
Suggest Change Button leads to 404

### ISSUE THREAD

**Issue by WhiteHotLoveTiger** [apache/airflow-site#436]
When I click on the "Suggest a change on this page" button, eg. from this page: https://airflow.apache.org/docs/apache-airflow/stable/concepts/taskflow.html , the button's link takes me to a 404 page on github like this one: https://github.com/apache/airflow/edit/devel/docs/apache-airflow/concepts/taskflow.rst

I believe the branch name in the link needs to be set to `main` instead of `devel`.

https://github.com/apache/airflow-site/blob/91f760cd62cb4b3aa5b40d455bed9ae694f7083d/sphinx_airflow_theme/sphinx_airflow_theme/suggest_change_button.html#L37-L39

**Comment by potiuk** [comment]
Yep. It is already fixed (see #417) - we just need to release new version of the documentation.

**Comment by potiuk** [comment]
Works now for providers (we released the docs). When we release Airfllow 2* it will be fixed for airflow/helm/docker-stack
