### ISSUE TITLE
dist.apache.org is not intended for public use

### ISSUE THREAD

**Issue by sebbASF** [apache/airflow-site#509]
The dist.apache.org host is only intended for use by ASF developers when staging and publishing releases.
It is not intended for use by the general public.

As such it should not appear on the announcements page: https://airflow.apache.org/announcements/

**Comment by potiuk** [comment]
Thanks ! It's fantastic to have someone to review this and flag it: 

I removed all the dist links!

https://github.com/apache/airflow-site/pull/510

**Comment by potiuk** [comment]
It's really great you help us in getting more compliant with ASF rules ! Kudos!

**Comment by potiuk** [comment]
If you find any more such problems - please let us know @sebbASF . This is really helpful.
