### ISSUE TITLE
Add automatic staging of changes for review

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow-site#52]

**Comment by potiuk** [comment]
Hello @mik-laj.  With the recent changes in https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/ and https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ we should be able to fully automate process of building and releasing the site. 

I believe this is one of the major blockers for the current site of apache airflow that it is not more alive - with sometimes outdated committer's list and very few blog posts. It's simply difficult to know if your change is working as expected, and most of all it is difficult to rebuild and publish the website after merge - only handful people have done it and it requires a separate environment and possibly a scary set of dependencies to update. 

If we have it fully automated i.e.:

1) Create pull request
2) Github Action builds the website automatically and publishes it as an artifact which you can download and verify without building it yourself 
3) After merge the website is built abd published automatically

Then the usefulness of the airflow website and its liveliness will be way better

@aijamalnk  -> maybe we could have a small follow up project sponsored by Google Cloud about that? That should take a week or so to develop I guess.

**Comment by potiuk** [comment]
cc: @mschickensoup
