### ISSUE TITLE
Usecases page has the same quote for two difference usecases

### ISSUE THREAD

**Issue by KevinAiken** [apache/airflow-site#523]
https://github.com/apache/airflow-site/blob/main/landing-pages/site/content/en/use-cases/adyen.md and https://github.com/apache/airflow-site/blob/main/landing-pages/site/content/en/use-cases/adobe.md both have the same quote at the top, attributed to different people. 

It's most obvious on this page, where you can see the duplicate quote on the top two use cases: https://airflow.apache.org/use-cases/

**Comment by eladkal** [comment]
I don't see the same quote. Can you show image?

**Comment by KevinAiken** [comment]
> I don't see the same quote. Can you show image?

Looks like it was fixed a couple of days ago by https://github.com/apache/airflow-site/pull/528. Going to go ahead and close this.

**Comment by Jorricks** [comment]
Yes this was a mistake from my end. Sorry guys.
