### ISSUE TITLE
Links to provider example dags are broken

### ISSUE THREAD

**Issue by jmelot** [apache/airflow-site#536]
The "view source" links in docs/apache_airflow seem fine, for example the example_kubernetes_executor link is ok here:

https://airflow.apache.org/docs/apache-airflow/stable/executor/kubernetes.html

but the "source" links for provider example dags are broken. For example, if you click on the "source" link for example_gcs_to_bigquery [here](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/cloud/gcs.html), it directs you to https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_modules/airflow/providers/google/cloud/example_dags/example_gcs_to_bigquery.html which is a 404. The same is true for the example_athena link [here](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/athena.html).

**Comment by potiuk** [comment]
Bump?

**Comment by mik-laj** [comment]
I think we should check this line:
https://github.com/apache/airflow/blob/c5ffe0c2dac14b940b600acaccda3b387ca14a28/docs/conf.py#L234-L236

**Comment by potiuk** [comment]
I looked at it, but I have no idea what it has to do with it :(

**Comment by mik-laj** [comment]
I looked at this problem and checked `ExampleLiteral` directive and it looks fine. However, the problem may be the use of the `sphinx.ext.code` module which does not make have a simple way to add a new module page and I can see some tricks are being used to integrate the directive with this extension.
Here are source code of `sphinx.ext.code` extension.
https://github.com/sphinx-doc/sphinx/blob/08a87d945a8ca7770c589ea878e9b095ed35e6d4/sphinx/ext/viewcode.py

**Comment by bhirsz** [comment]
In linked issue similiar problem. All links to source code are dead. Hovewer we can probably track the origin - for example those links are dead:

https://airflow.apache.org/docs/apache-airflow/2.3.0/_modules/airflow/example_dags/example_external_task_marker_dag.html

https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/example_dags/example_external_task_marker_dag.html

But this one works:
https://airflow.apache.org/docs/apache-airflow/2.2.3/_modules/airflow/example_dags/example_external_task_marker_dag.html

Something between Airflow 2.2.3 and 2.3.0 caused this issue (for this particular link. We could have dead links for longer period of time).

On side note it would be worth to add very simple ui tests - just parse all links on the site and check if any is 404.

**Comment by bhirsz** [comment]
It can be used to test links: 
https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder

I can try to do it but only after next few days.
