### ISSUE TITLE
some docs tables are not aligned

### ISSUE THREAD

**Issue by alexInhert** [apache/airflow-site#552]
### Description

![Screen Shot 2022-02-24 at 14 43 56](https://user-images.githubusercontent.com/62940116/155526569-137dd4c8-c792-4ea2-a04d-a392dfb40a4e.png)

https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html

It's not easy to read it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jmelot** [comment]
I just came here to report this too. I encountered it [here](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/operators/bigquery/index.html). Looks like the first column is getting a width of 10%.

<img width="950" alt="Screen Shot 2022-03-22 at 8 51 59 AM" src="https://user-images.githubusercontent.com/1252409/159486381-46f2ee1d-50e8-49bb-b7bc-5d05f7c24922.png">

It looks _much_ better with a width of e.g. 40%.

<img width="1172" alt="Screen Shot 2022-03-22 at 8 52 33 AM" src="https://user-images.githubusercontent.com/1252409/159486458-a19bd9de-04bf-418f-8686-a27a90e1cbce.png">

I can submit a PR (hopefully this evening, in any case sometime this week)

**Comment by potiuk** [comment]
> I can submit a PR (hopefully this evening, in any case sometime this week)

Would be cool. It bothers me too :)

**Comment by josh-fell** [comment]
@alexInhert I've spot-checked several Python API pages for both core and providers and it seems like this is fixed now. Would you mind taking a look when you have a chance?
