### ISSUE TITLE
why the home page can‘t in？

### ISSUE THREAD

**Issue by looperEit** [apache/airflow-site#591]
![image](https://user-images.githubusercontent.com/46367388/167858277-44e064ec-9295-4a8c-a7be-66745cbf978d.png)
i start the airflow and i can't get in the home page.
![image](https://user-images.githubusercontent.com/46367388/167858516-4e317cec-22e1-4990-881c-45508ca2bde5.png)

**Comment by potiuk** [comment]
Closing. No way we can help with that.
