### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool(host='cloud.getdbt.com', port=443) while connecting to dbt cloud

### ISSUE THREAD

**Issue by rajans163** [apache/airflow-site#612]
Hi All..I am trying to connect dbt cloud using airflow but getting this error

requests.exceptions.SSLError: HTTPSConnectionPool(host='cloud.getdbt.com', port=443):

**Comment by potiuk** [comment]
Not, the place to open it (this is doc repo), and please don't open issue for that - just [discussion](https://github.com/apache/airflow/discussions) if you want to get some troubleshooting help
