### ISSUE TITLE
Possible incomplete page published.

### ISSUE THREAD

**Issue by ashshuota** [apache/airflow-site#677]
The [installation page](https://airflow.apache.org/install/) contains a lot of boilerplate content and missing links and by no means is ready for production.

**Comment by potiuk** [comment]
Thanks!. Not sure how you got there - because this (apparently old and unlinked) page does not seem to be linked anywhere. Added #678 to remove it.

**Comment by potiuk** [comment]
fixed version should be up in ~10 minutes

**Comment by ashshuota** [comment]
This is the first link that appears on duckduckgo search results when searched for "apache airflow install". Fortunately, does not seem to be the case for google.

**Comment by potiuk** [comment]
<img width="436" alt="Screenshot 2022-10-27 at 09 41 29" src="https://user-images.githubusercontent.com/595491/198221433-e171caf7-95fd-456e-8357-4b8dd3fb63a6.png">

Gone now. Thanks again!
