### ISSUE TITLE
slack community link down

### ISSUE THREAD

**Issue by mlineen** [apache/airflow-site#689]
https://github.com/apache/airflow-site/blob/45db8c0f01f562008bafea2955f678b8e88cdf8a/landing-pages/site/content/en/community/_index.html#L44

Links to https://apache-airflow-slack.herokuapp.com which is down likely due to this https://devcenter.heroku.com/articles/free-dyno-hours

**Comment by potiuk** [comment]
Yep this is because of Heroku. Awareness of it is raised in (yes!) slack https://apache-airflow.slack.com/archives/CCPRP7943/p1669997653608189  and we need some @kaxil and @ashb help with setting it up in a new place.

**Comment by kaxil** [comment]
Yup, I am on it

**Comment by potiuk** [comment]
> Yup, I am on it

Any help needed (testing?), I am here  :)

**Comment by kaxil** [comment]
Should be back, try adding an email

**Comment by potiuk** [comment]
Thanks @kaxil :)
