### ISSUE TITLE
Docs site making request to globaltoc.js but it doesn't exist

### ISSUE THREAD

**Issue by amoghrajesh** [apache/airflow-site#713]
### What do you see as an issue?

Most pages on the airflow docs are making API calls to `globaltoc.js` and the file doesn't exist anymore leading to these requests being repetitive and exiting with 404 status code. This also results in an ugly browser console flooded with these 404 errors. 
For example:
![image](https://user-images.githubusercontent.com/35884252/208465076-c8040ff7-3aa6-451a-ac58-3d01fc95aca5.png)

### Solving the problem

The problem can be solved by disabling the calls to this endpoint so that the calls don't go and the error doesn't come

### Anything else

Issue happens at intervals when on **any** airflow doc page

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Transferred this issue to the right repo.

**Comment by amoghrajesh** [comment]
Thanks @potiuk 
Can you give me a hint where to make changes?

**Comment by potiuk** [comment]
I do not know the framework good enough to give advices on it - I think it needs a bit searching where it is used and why it is gone - I bet it was working before. So part of this issue is also to find out where to change it and how I am afraid.
