### ISSUE TITLE
Ecosystem Link in Nav goes to the wrong page.

### ISSUE THREAD

**Issue by johnstonmatt** [apache/airflow-site#720]
The blue "Ecosystem" button in the nav on the landing page links to:

https://airflow.apache.org/docs/apache-airflow/stable/start.html

instead of

https://airflow.apache.org/ecosystem/

This is the button:

<img width="1728" alt="Screenshot 2023-01-05 at 6 37 55 PM" src="https://user-images.githubusercontent.com/5455542/210893789-be65cd98-2ecd-4100-82ad-7a64f0ce94de.png">

**Comment by potiuk** [comment]
Should be fixed in a few minutes when the sites rebuild itself.s Thanks @johnstonmatt for reporting it!

**Comment by potiuk** [comment]
It's fixed now.
