### ISSUE TITLE
The navigation bar covers part of the main container

### ISSUE THREAD

**Issue by hussein-awala** [apache/airflow-site#769]
It appears that the website pages' main containers lack dynamism. When we added the Airflow summit add-on at the top of the page, the navigation bar shifted downwards, but the main container for each page remained static.

![image](https://user-images.githubusercontent.com/21311487/232463234-6fdb86a0-a04b-40a0-b239-b017f9ba1a5f.png)

**Comment by potiuk** [comment]
Yep. It's a known issue. it's been like that every time we put the banner and we never gotten to fixing it. Needs someone with css skills. cc: @bbovenzi

**Comment by mayankjain2710** [comment]
i am interested to solve this issue. can i do this if nobody assigned this issue

**Comment by potiuk** [comment]
> i am interested to solve this issue. can i do this if nobody assigned this issue

It's completed.
