### ISSUE TITLE
Add dark theme, by @prefers-color-theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [apache/airflow-site#803]
### What do you see as an issue?

For many users - difficult to read from the white background. Especially at low light conditions.

### Solving the problem

By leveraging this CSS media query https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vitaly-zdanevich** [comment]
Maybe...

**Comment by pierrejeambrun** [comment]
@vitaly-zdanevich just assigned you :)

**Comment by porwalshreyaa** [comment]
Hey @vitaly-zdanevich, are you still working on it? Or else I am willing to take this issue as no dark mode is too much trouble for me 😢😭

**Comment by eladkal** [comment]
@porwalshreyaa assigned to you

**Comment by vitaly-zdanevich** [comment]
Hi, I am not using Airflow now, feel free to do it as you want...

**Comment by mayo7e** [comment]
@eladkal  @porwalshreyaa  i'll like to join in on this , see if we can get this done in a short time., this is a real blocker for me too.

**Comment by potiuk** [comment]
Feel free @mayo7e -> dark mode is added already in upcoming Airflow 2.10 -> https://github.com/apache/airflow/pull/39355, already works in main, probably what is needed is to enable it automatically by `@prefers-color-theme` -> if it does not work like that already.

**Comment by potiuk** [comment]
BTW. The PR for dark mode got the title of "PR of the month" in June unanimously, so you are not the only want that considered that as a blocker - see  https://lists.apache.org/thread/fnlswr7w69oofxp6g8rkc5052yxc7rs2

**Comment by porwalshreyaa** [comment]
@potiuk why did you unassign me? I am still working on it and he asked to join me, maybe you could just assign us both?

**Comment by potiuk** [comment]
Ups. FAT FINGERS

**Comment by mayo7e** [comment]
@potiuk greta , on it!

**Comment by porwalshreyaa** [comment]
@potiuk Thanks! I've told my friends that I am working on this, if I don't get to merge, I'll be in trouble 😂

**Comment by mayo7e** [comment]
@porwalshreyaa   happy to work with you on this! Is there a feature branch you already created that I can clone? If you have the tasks defined, I can get started with a task right away. If not, perhaps we can start by defining the tasks together.

**Comment by porwalshreyaa** [comment]
@mayo7e I haven't created a branch yet, I just read the mdn doc. Maybe we can do divide pages you can do one page completely by yourself and I'll do another, or you have something else in mind? I am yet to define tasks

**Comment by mayo7e** [comment]
@porwalshreyaa  Perhaps you can point me to the MDN documentation in question so I can get up to speed. I'm not sure what you mean by "divide pages." According to @potiuk , all that remains is adding the functionality for OS theme preference to be reflected in the Airflow UI while still keeping the toggle button option available.

**Comment by porwalshreyaa** [comment]
@mayo7e [mdn css preference](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by porwalshreyaa** [comment]
@mayo7e by divide I meant to distribute tasks among us

**Comment by mayo7e** [comment]
@porwalshreyaa Alright, I'll take some time to go over the documentation and share my thoughts on how we can divide the tasks.

**Comment by mayo7e** [comment]
> @mayo7e [mdn css preference](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

thanks

**Comment by porwalshreyaa** [comment]
@potiuk I am reading the code rn. Let's discuss it after we are both done. Btw, right now it's 5.30 pm in India. Are you available 4-5 hours later or it'll be too late for you to discuss?

**Comment by mayo7e** [comment]
@porwalshreyaa  4/5 hrs sounds fine. i will be doing same with the code...

**Comment by potiuk** [comment]
> @potiuk I am reading the code rn. Let's discuss it after we are both done. Btw, right now it's 5.30 pm in India. Are you available 4-5 hours later or it'll be too late for you to discuss?

I have almost no knowledge there to discuss and we usually discuss things offline in PRs, I doubt there is a need for synchronous call and spending time of few people trying to set-it-up on call while it can be discussed offline

**Comment by potiuk** [comment]
:D

**Comment by mayo7e** [comment]
@potiuk I think this has been implemented already, having to run an upgrade on my ram so i can run locally via docker to test.  Also watched your demo  at the recent community meet on this..

**Comment by potiuk** [comment]
Yes. I think having it persistent (rather than use media query) is good enough.,
