### ISSUE TITLE
If yarn is not preinstalled, local build fails.

### ISSUE THREAD

**Issue by choo121600** [apache/airflow-site#901]
## What do you see as an issue?
If yarn is not pre-installed when building local, the build will fail.

![스크린샷 2023-12-04 오전 3 39 27](https://github.com/apache/airflow-site/assets/54111883/464d57fb-5f79-4ae4-9cbf-17ba8bc40f10)

## How to solve
Run ```brew install yarn``` before ```bash site.sh build-site```

![스크린샷 2023-12-04 오전 3 40 24](https://github.com/apache/airflow-site/assets/54111883/9c83f788-94cd-4eed-a100-c7a8dfafc6e7)

## Are you willing to submit PR?
- [X] Yes I am willing to submit a PR!

## Code of Conduct
- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment]
thanks, closing as solved
