### ISSUE TITLE
Issue with Unreachable Page Due to Page Address Error

### ISSUE THREAD

**Issue by thisistorr** [apache/airflow-site#903]
Hello, This is Torr.

I am writing to report an issue I encountered while attempting to access the linked website. Unfortunately, I received a "The page you were looking for couldn't be found" message, preventing me from accessing the intended page.

![image](https://github.com/apache/airflow-site/assets/68784313/a27f1e25-46fd-48f5-b99c-5f84cc1ede76)

Expected Behavior:
I expected to be redirected to the correct page without any errors.

**Comment by eladkal** [comment]
fixed in https://github.com/apache/airflow-site/pull/904
