### ISSUE TITLE
Conflict Between Yarn Installation Locally and Hadoop YARN

### ISSUE THREAD

**Issue by cpprhtn** [apache/airflow-site#909]
**Description:**
Encountering a conflict between the `Hadoop YARN` environment and the Yarn package manager required for building the Airflow website.

To resolve this conflict, it is recommended to use the alias `yarnpkg` when installing Yarn.

**References:**
https://github.com/yarnpkg/yarn/issues/673
https://github.com/yarnpkg/yarn/commit/cefa9a368dd3df1a1f1ecd9e50de9c5fabefbc92

**Comment by pierrejeambrun** [comment]
Closing, cf https://github.com/apache/airflow-site/pull/910 for more context.
