### ISSUE TITLE
Removal of project specific privacy page

### ISSUE THREAD

**Issue by grobmeier** [apache/airflow-site#917]
Hello,

the use of Google Analytics is discouraged at the ASF.
You can completely remove this page:
https://airflow.apache.org/privacy-notice/

And direct your users to:
https://privacy.apache.org/policies/privacy-policy-public.html

The Airflow project already uses ASF Matomo, so maybe this page is just a leftover from old days.

**Comment by potiuk** [comment]
Yep. It is indeed. Thanks for notifying us.

**Comment by potiuk** [comment]
Will be fixed in https://github.com/apache/airflow-site/pull/919 and in the airflow content https://github.com/apache/airflow/pull/36394 when we release Airflow next time (it's linked in the footers).
