### ISSUE TITLE
Airflow community page looks bad on mobile

### ISSUE THREAD

**Issue by eladkal** [apache/airflow-site#934]
**Desktop:**

<img width="1452" alt="Screenshot 2024-01-15 at 14 19 04" src="https://github.com/apache/airflow-site/assets/45845474/2fb642da-b116-4fa8-ac22-c6a429083a05">

------

**Mobile:**

![mobile](https://github.com/apache/airflow-site/assets/45845474/a4560470-13a2-47f2-bc7d-ae96ac6c5083)

**Comment by potiuk** [comment]
cc: @merobi-hub :)

**Comment by merobi-hub** [comment]
[935](https://github.com/apache/airflow-site/pull/935) will close this.

**Comment by eladkal** [comment]
Nice! Thank you!
