### ISSUE TITLE
Search Function in the Blog page is not working

### ISSUE THREAD

**Issue by Satoshi-Sh** [apache/airflow-site#954]
## Issues 
When you search [Blog page](https://airflow.apache.org/blog/) for any word (ex. airflow), it does not work properly. 

![Screenshot from 2024-02-14 17-44-41](https://github.com/apache/airflow-site/assets/73622805/25389381-859c-427c-8dbc-695467f33c41)

It's supposed to return related matched posts by keyword.

## Additional Information
This PR #956 fixed a related bug when the URL doesn't have a query like https://airflow.apache.org/blog?q=airflow

**Comment by xionams** [comment]
the search function works well
@Satoshi-Sh what do you think?

**Comment by Satoshi-Sh** [comment]
It doesn't show the error anymore. I will close this. @xionams
