### ISSUE TITLE
Typo for Helm Chart URL

### ISSUE THREAD

**Issue by allekai** [apache/airflow-site#962]
Hey there,

it seems there is a typo in the URL for the Helm Chart Release Announcement version 1.12.0
 https://airflow.apache.org/announcements/

> 
> February 12, 2024
> 
> We’ve just released Apache Airflow Helm chart 1.12.0.
> 
> 📦 ArtifactHub: https://artifacthub.io/packages/helm/apache-airflow/airflow
> 📚 Docs: https://airflow.apache.org/docs/helm-chart/1.12.0/
> 🛠️ Release Notes: https://airflow.apache.org/docs/helmrchart/1.12.0/release_notes.html        <------
> 🪶 Sources: https://airflow.apache.org/docs/helm-chart/1.12.0/installing-helm-chart-from-sources.html

Should be **https://airflow.apache.org/docs/helm-chart/1.12.0/release_notes.html** instead.

Best regards

**Comment by slmg** [comment]
Also true for `1.13.0` and `1.13.1` releases.
https://github.com/apache/airflow-site/blob/5255a77d93f8e74209bee300cb87e31c3d95665d/landing-pages/site/content/en/announcements/_index.md?plain=1#L31

**Comment by potiuk** [comment]
Why don't one of you make a PR to fix it @allekai @slmg ? It's as easy as clicking "Suggest a change on this page"  (bottom right) and fixing the typo using GitHub UI. Can we count on your help ?

**Comment by slmg** [comment]
Hi @potiuk , happy to make a PR. I was not sure if fixing the typo in the file I shared was enough or if the typo existed on any template used to render the announcement.

**Comment by potiuk** [comment]
> Hi @potiuk , happy to make a PR. I was not sure if fixing the typo in the file I shared was enough or if the typo existed on any template used to render the announcement.

You can check here https://github.com/apache/airflow/blob/main/dev/README_RELEASE_HELM_CHART.md
